// import { Event, EventStatus, EventType } from "../models/event";

// export class EventData {
//   static todayEvents: Event[] = [
//     {
//       id: 1,
//       name: 'Football Match',
//       description: 'Inter-university football tournament semi-finals.',
//       imageUrl: 'https://www.fisu.net/app/uploads/2023/10/paulista_university1.jpg',
//       startTime: '2024-12-29T15:00:00',
//       endTime: '2024-12-29T17:00:00',
//       room: 'University Stadium',
//       capacity: 500,
//       location: "Some location",
//       going: 300,
//       interested: 100,
//       declined: 50,
//       status: EventStatus.AVAILABLE,
//       price: 5,
//       type: EventType.SPORTS,
//     },
//     {
//       id: 2,
//       name: 'Freshers Party',
//       description: 'Welcoming all the freshers with music, dance, and games.',
//       imageUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTE7luLlquO6JGKRCKH8jvKJ3x8ic4gOS4jxg&s',
//       startTime: '2024-12-29T19:00:00',
//       endTime: '2024-14-29T23:00:00',
//       room: 'Main Hall',
//       capacity: 200,
//       location: "Some location",
//       going: 150,
//       interested: 30,
//       declined: 20,
//       status: EventStatus.AVAILABLE,
//       price: 10,
//       type: EventType.PARTY,
//     },
//     {
//       id: 3,
//       name: 'Tech Conference 2024',
//       description: 'Discussing the future of AI and machine learning.',
//       imageUrl: 'https://example.com/tech_conference.jpg',
//       startTime: '2024-12-29T10:00:00',
//       endTime: '2024-12-29T16:00:00',
//       room: 'Auditorium',
//       capacity: 300,
//       location: "Some location",
//       going: 250,
//       interested: 30,
//       declined: 20,
//       status: EventStatus.AVAILABLE,
//       price: 15,
//       type: EventType.CONFERENCE,
//     },
//     {
//       id: 4,
//       name: 'Painting Workshop',
//       description: 'Learn painting techniques from professionals.',
//       imageUrl: 'https://example.com/painting_workshop.jpg',
//       startTime: '2024-12-29T14:00:00',
//       endTime: '2024-12-29T17:00:00',
//       room: 'Art Studio',
//       capacity: 25,
//       location: "Some location",
//       going: 20,
//       interested: 3,
//       declined: 2,
//       status: EventStatus.FINISHED,
//       price: 10,
//       type: EventType.WORKSHOP,
//     },
//     {
//       id: 5,
//       name: 'Cultural Fest',
//       description: 'Experience a blend of music, dance, and traditions.',
//       imageUrl: 'https://example.com/cultural_fest.jpg',
//       startTime: '2024-12-29T17:00:00',
//       endTime: '2024-12-29T22:00:00',
//       room: 'Open Grounds',
//       capacity: 1000,
//       location: "Some location",
//       going: 800,
//       interested: 150,
//       declined: 50,
//       status: EventStatus.AVAILABLE,
//       price: 0,
//       type: EventType.CULTURAL,
//     },
//     {
//       id: 6,
//       name: 'Guest Lecture on Space Exploration',
//       description: 'Hear from NASA scientists about the future of space exploration.',
//       imageUrl: 'https://example.com/guest_lecture.jpg',
//       startTime: '2024-12-29T15:00:00',
//       endTime: '2024-12-29T16:30:00',
//       room: 'Lecture Hall 1',
//       capacity: 100,
//       location: "Some location",
//       going: 90,
//       interested: 5,
//       declined: 5,
//       status: EventStatus.AVAILABLE,
//       price: 0,
//       type: EventType.ACADEMIC,
//     },
//   ];

//   static thisWeekEvents: Event[] = [
//     {
//       id: 7,
//       name: 'Football Match',
//       description: 'Inter-university football tournament semi-finals.',
//       imageUrl: 'https://example.com/football_match.jpg',
//       startTime: '2024-12-30T15:00:00',
//       endTime: '2024-12-30T17:00:00',
//       room: 'University Stadium',
//       capacity: 500,
//       location: "Some location",
//       going: 300,
//       interested: 100,
//       declined: 50,
//       status: EventStatus.AVAILABLE,
//       price: 5,
//       type: EventType.SPORTS,
//     },
//     {
//       id: 8,
//       name: 'Tech Conference 2024',
//       description: 'Discussing the future of AI and machine learning.',
//       imageUrl: 'https://example.com/tech_conference.jpg',
//       startTime: '2024-12-31T10:00:00',
//       endTime: '2024-12-31T16:00:00',
//       room: 'Auditorium',
//       capacity: 300,
//       location: "Some location",
//       going: 250,
//       interested: 30,
//       declined: 20,
//       status: EventStatus.AVAILABLE,
//       price: 15,
//       type: EventType.CONFERENCE,
//     },
//     {
//       id: 9,
//       name: 'Freshers Party',
//       description: 'Welcoming all the freshers with music, dance, and games.',
//       imageUrl: 'https://example.com/freshers_party.jpg',
//       startTime: '2024-12-30T19:00:00',
//       endTime: '2024-12-30T23:00:00',
//       room: 'Main Hall',
//       capacity: 200,
//       location: "Some location",
//       going: 150,
//       interested: 30,
//       declined: 20,
//       status: EventStatus.AVAILABLE,
//       price: 10,
//       type: EventType.PARTY,
//     },
//     {
//       id: 10,
//       name: 'Cultural Fest',
//       description: 'Experience a blend of music, dance, and traditions.',
//       imageUrl: 'https://example.com/cultural_fest.jpg',
//       startTime: '2024-12-31T17:00:00',
//       endTime: '2024-12-31T22:00:00',
//       room: 'Open Grounds',
//       capacity: 1000,
//       location: "Some location",
//       going: 800,
//       interested: 150,
//       declined: 50,
//       status: EventStatus.AVAILABLE,
//       price: 0,
//       type: EventType.CULTURAL,
//     },
//   ];

//   static thisMonthEvents: Event[] = [
//     {
//       id: 11,
//       name: 'Football Match',
//       description: 'Inter-university football tournament semi-finals.',
//       imageUrl: 'https://example.com/football_match.jpg',
//       startTime: '2024-12-30T15:00:00',
//       endTime: '2024-12-30T17:00:00',
//       room: 'University Stadium',
//       capacity: 500,
//       location: "Some location",
//       going: 300,
//       interested: 100,
//       declined: 50,
//       status: EventStatus.AVAILABLE,
//       price: 5,
//       type: EventType.SPORTS,
//     },
//     {
//       id: 12,
//       name: 'Tech Conference 2024',
//       description: 'Discussing the future of AI and machine learning.',
//       imageUrl: 'https://example.com/tech_conference.jpg',
//       startTime: '2024-12-31T10:00:00',
//       endTime: '2024-12-31T16:00:00',
//       room: 'Auditorium',
//       capacity: 300,
//       location: "Some location",
//       going: 250,
//       interested: 30,
//       declined: 20,
//       status: EventStatus.AVAILABLE,
//       price: 15,
//       type: EventType.CONFERENCE,
//     },
//     {
//       id: 13,
//       name: 'New Year Party',
//       description: 'Celebrate the new year with music and dancing.',
//       imageUrl: 'https://example.com/new_year_party.jpg',
//       startTime: '2024-12-31T20:00:00',
//       endTime: '2025-01-01T01:00:00',
//       room: 'Main Hall',
//       capacity: 300,
//       location: "Some location",
//       going: 200,
//       interested: 50,
//       declined: 10,
//       status: EventStatus.AVAILABLE,
//       price: 20,
//       type: EventType.PARTY,
//     },
//     {
//       id: 14,
//       name: 'Workshop on Machine Learning',
//       description: 'Learn the basics of machine learning and AI technologies.',
//       imageUrl: 'https://example.com/machine_learning_workshop.jpg',
//       startTime: '2024-12-28T09:00:00',
//       endTime: '2024-12-28T16:00:00',
//       room: 'Computer Lab 1',
//       capacity: 30,
//       location: "Some location",
//       going: 25,
//       interested: 10,
//       declined: 5,
//       status: EventStatus.AVAILABLE,
//       price: 25,
//       type: EventType.WORKSHOP,
//     },
//   ];
// }
